apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-nd
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - protocol:
      port: 8080
      targetPort: 80
      nodePort: 30080 # range 30000-32767
  type: NodePort