apiVersion : v1
kind: Pod
metadata:
  name: test-web-servers
  labels:
    env: prod
    app: main
    tier: web-server
    owner: DarthVader
spec:
  containers:
    - name: cont-nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    
    - name: cont-tomcat
      image: tomcat:8.5.38
      ports:
        - containerPort: 8080