apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5  # defaults to 0 seconds. Minimum value is 0.
          periodSeconds: 5        # default to 10 sec. Min value is 1.
          timeoutSeconds: 1       # default to 10 sec. Min value is 1.
          successThreshold: 1     # default to 1. Must ve 1 for liveness and startup Probes. Min value is 1.
          failureThreshold: 3     # default to 3. Min value is 1.