apiVersion: apps/v1
kind: Deployment
metadata:
  name: death-star-deploy
  labels:
    app: deathStar
    env: prod
    owner: DarthVader
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: deathStar
  template:
    metadata:
      labels:
        app: deathStar
    spec:
      containers:
        - name: death-star
          image: mustafaevsl/k8s-php-test:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-death-star
spec:
  selector:
    app: deathStar
  ports:
    - protocol:
      port: 8080
      targetPort: 80
      nodePort: 30080 # range 30000-32767
  type: NodePort
