apiVersion: apps/v1
kind: Deployment
metadata:
  name: death-star-deploy
  labels:
    app: deathStar
    env: prod
    owner: DarthVader
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: deathStar
  template:
    metadata:
      labels:
        app: deathStar
    spec:
      containers:
        - name: death-star
          image: mustafaevsl/k8s-php-test:latest
          ports:
            - containerPort: 80
          startubProbe:
            exec:
              command:
              - cat
              - /var/www/html/index.php
            initialDelaySeconds: 10
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - cat
              - /var/www/html/index.php
            failureThreshold: 1
            periodSeconds: 10
#           livenessProbe:                        
#             httpGet:
#               path: /
#               httpHeaders:                           # роутит трафик на уровне хостов
#               - name: Host
#                 value: kuber-app.example.com
#               port: 80
#             initialDelaySeconds: 5
#             periodSeconds: 5
# ---
apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-death-star
spec:
  selector:
    app: deathStar
  ports:
    - protocol:
      port: 8080
      targetPort: 80
      nodePort: 30080 # range 30000-32767
  type: NodePort
